/**
 * Migration runner.
 *
 * Reads `migrations/*.sql` (generated by `drizzle-kit generate`) and
 * applies any that haven't been recorded in Drizzle's `__drizzle_migrations`
 * tracking table yet. Idempotent — safe to run on every deploy.
 *
 * Invoked via `npm run db:migrate` locally, and as the Railway release
 * command in production so the schema lands before the new app revision
 * starts serving requests.
 */

// On Railway the platform injects env vars natively, so dotenv would
// be dead weight. For local dev pass DATABASE_URL explicitly:
//   DATABASE_URL=postgres://... npm run db:migrate
// or use Node's built-in `--env-file=.env.local` flag via:
//   node --env-file=.env.local --import tsx scripts/migrate.ts
import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { Pool } from 'pg';

async function main() {
  const url = process.env.DATABASE_URL;
  if (!url) {
    // Soft-skip so the runtime `start` script can chain
    // `npm run db:migrate && next start` even on deploys that haven't
    // attached a Postgres service yet — the panel falls back to the
    // legacy file-only code paths in that mode.
    console.warn('[migrate] DATABASE_URL not set — skipping (legacy file-only mode)');
    process.exit(0);
  }

  const pool = new Pool({
    connectionString: url,
    // Mirror the SSL policy from src/lib/server/db: Railway-style
    // self-signed certs accepted by default in production; operators
    // can flip DATABASE_SSL_REJECT_UNAUTHORIZED=true once they have
    // a real CA bundle. Dev runs over plain TCP.
    ssl:
      process.env.NODE_ENV === 'production'
        ? {
            rejectUnauthorized:
              process.env.DATABASE_SSL_REJECT_UNAUTHORIZED === 'true',
          }
        : false,
  });

  const db = drizzle(pool);
  console.log('[migrate] applying pending migrations…');
  await migrate(db, { migrationsFolder: './migrations' });
  console.log('[migrate] done');
  await pool.end();
}

main().catch((err) => {
  console.error('[migrate] failed:', err);
  process.exit(1);
});
